[
    [
        ["MSH"],
        ["|"],
        ["^"],
        ["BC-5380"],
        ["Mindray"],
        [""],
        [""],
        ["20210202151447"],
        [""],
        [[["ORU"], ["R01"]]],
        ["87"],
        ["P"],
        ["2.3.1"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["UNICODE\nPID"],
        ["1"],
        [""],
        [""],
        [""],
        ["\nPV1"],
        ["1"],
        [""],
        ["\nOBR"],
        ["1"],
        [""],
        ["155"],
        [[["00001"], ["Automated Count"], ["99MRC"]]],
        [""],
        [""],
        ["20210202151339"],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["HM"],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["Service Engineer\nOBX"],
        ["1"],
        ["IS"],
        [[["08001"], ["Take Mode"], ["99MRC"]]],
        [""],
        ["C"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["2"],
        ["IS"],
        [[["08002"], ["Blood Mode"], ["99MRC"]]],
        [""],
        ["W"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["3"],
        ["IS"],
        [[["08003"], ["Test Mode"], ["99MRC"]]],
        [""],
        ["CBC DIFF"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["4"],
        ["IS"],
        [[["01002"], ["Ref Group"], ["99MRC"]]],
        [""],
        ["General"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["5"],
        ["NM"],
        [[["6690-2"], ["WBC"], ["LN"]]],
        [""],
        ["3.91"],
        ["10*9/L"],
        ["4.00-10.00"],
        ["L"],
        [""],
        [""],
        ["F\nOBX"],
        ["6"],
        ["NM"],
        [[["704-7"], ["BAS#"], ["LN"]]],
        [""],
        ["0.03"],
        ["10*9/L"],
        ["0.00-0.10"],
        [["N"], ["A"]],
        [""],
        [""],
        ["F\nOBX"],
        ["7"],
        ["NM"],
        [[["706-2"], ["BAS%"], ["LN"]]],
        [""],
        ["0.8"],
        ["%"],
        ["0.0-1.0"],
        [["N"], ["A"]],
        [""],
        [""],
        ["F\nOBX"],
        ["8"],
        ["NM"],
        [[["751-8"], ["NEU#"], ["LN"]]],
        [""],
        ["2.31"],
        ["10*9/L"],
        ["2.00-7.00"],
        [["N"], ["A"]],
        [""],
        [""],
        ["F\nOBX"],
        ["9"],
        ["NM"],
        [[["770-8"], ["NEU%"], ["LN"]]],
        [""],
        ["59.1"],
        ["%"],
        ["50.0-70.0"],
        [["N"], ["A"]],
        [""],
        [""],
        ["F\nOBX"],
        ["10"],
        ["NM"],
        [[["711-2"], ["EOS#"], ["LN"]]],
        [""],
        ["0.16"],
        ["10*9/L"],
        ["0.02-0.50"],
        [["N"], ["A"]],
        [""],
        [""],
        ["F\nOBX"],
        ["11"],
        ["NM"],
        [[["713-8"], ["EOS%"], ["LN"]]],
        [""],
        ["4.0"],
        ["%"],
        ["0.5-5.0"],
        [["N"], ["A"]],
        [""],
        [""],
        ["F\nOBX"],
        ["12"],
        ["NM"],
        [[["731-0"], ["LYM#"], ["LN"]]],
        [""],
        ["1.27"],
        ["10*9/L"],
        ["0.80-4.00"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["13"],
        ["NM"],
        [[["736-9"], ["LYM%"], ["LN"]]],
        [""],
        ["32.4"],
        ["%"],
        ["20.0-40.0"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["14"],
        ["NM"],
        [[["742-7"], ["MON#"], ["LN"]]],
        [""],
        ["0.14"],
        ["10*9/L"],
        ["0.12-1.20"],
        [["N"], ["A"]],
        [""],
        [""],
        ["F\nOBX"],
        ["15"],
        ["NM"],
        [[["5905-5"], ["MON%"], ["LN"]]],
        [""],
        ["3.7"],
        ["%"],
        ["3.0-12.0"],
        [["N"], ["A"]],
        [""],
        [""],
        ["F\nOBX"],
        ["16"],
        ["NM"],
        [[["26477-0"], ["*ALY#"], ["LN"]]],
        [""],
        ["0.00"],
        ["10*9/L"],
        ["0.00-0.20"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["17"],
        ["NM"],
        [[["13046-8"], ["*ALY%"], ["LN"]]],
        [""],
        ["0.1"],
        ["%"],
        ["0.0-2.0"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["18"],
        ["NM"],
        [[["10000"], ["*LIC#"], ["99MRC"]]],
        [""],
        ["0.00"],
        ["10*9/L"],
        ["0.00-0.20"],
        [["N"], ["A"]],
        [""],
        [""],
        ["F\nOBX"],
        ["19"],
        ["NM"],
        [[["10001"], ["*LIC%"], ["99MRC"]]],
        [""],
        ["0.0"],
        ["%"],
        ["0.0-2.5"],
        [["N"], ["A"]],
        [""],
        [""],
        ["F\nOBX"],
        ["20"],
        ["NM"],
        [[["789-8"], ["RBC"], ["LN"]]],
        [""],
        ["4.84"],
        ["10*12/L"],
        ["3.50-5.50"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["21"],
        ["NM"],
        [[["718-7"], ["HGB"], ["LN"]]],
        [""],
        ["13.8"],
        ["g/dL"],
        ["11.0-16.0"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["22"],
        ["NM"],
        [[["787-2"], ["MCV"], ["LN"]]],
        [""],
        ["89.0"],
        ["fL"],
        ["80.0-100.0"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["23"],
        ["NM"],
        [[["785-6"], ["MCH"], ["LN"]]],
        [""],
        ["28.4"],
        ["pg"],
        ["27.0-34.0"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["24"],
        ["NM"],
        [[["786-4"], ["MCHC"], ["LN"]]],
        [""],
        ["31.9"],
        ["g/dL"],
        ["32.0-36.0"],
        ["L"],
        [""],
        [""],
        ["F\nOBX"],
        ["25"],
        ["NM"],
        [[["788-0"], ["RDW-CV"], ["LN"]]],
        [""],
        ["12.5"],
        ["%"],
        ["11.0-16.0"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["26"],
        ["NM"],
        [[["21000-5"], ["RDW-SD"], ["LN"]]],
        [""],
        ["46.6"],
        ["fL"],
        ["35.0-56.0"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["27"],
        ["NM"],
        [[["4544-3"], ["HCT"], ["LN"]]],
        [""],
        ["0.431"],
        [""],
        ["0.370-0.540"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["28"],
        ["NM"],
        [[["777-3"], ["PLT"], ["LN"]]],
        [""],
        ["204"],
        ["10*9/L"],
        ["100-300"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["29"],
        ["NM"],
        [[["32623-1"], ["MPV"], ["LN"]]],
        [""],
        ["8.8"],
        ["fL"],
        ["6.5-12.0"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["30"],
        ["NM"],
        [[["32207-3"], ["PDW"], ["LN"]]],
        [""],
        ["16.0"],
        [""],
        ["9.0-17.0"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["31"],
        ["NM"],
        [[["10002"], ["PCT"], ["99MRC"]]],
        [""],
        ["0.179"],
        ["%"],
        ["0.108-0.282"],
        ["N"],
        [""],
        [""],
        ["F\nOBX"],
        ["32"],
        ["IS"],
        [[["17790-7"], ["WBC Left Shift?"], ["LN"]]],
        [""],
        ["T"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["33"],
        ["IS"],
        [[["34165-1"], ["Imm Granulocytes?"], ["LN"]]],
        [""],
        ["T"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["34"],
        ["NM"],
        [[["15001"], ["WBC Histogram. Left Line"], ["99MRC"]]],
        [""],
        ["12"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["35"],
        ["NM"],
        [[["15002"], ["WBC Histogram. Right Line"], ["99MRC"]]],
        [""],
        ["72"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["36"],
        ["NM"],
        [[["15003"], ["WBC Histogram. Middle Line"], ["99MRC"]]],
        [""],
        ["40"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["37"],
        ["NM"],
        [[["15004"], ["WBC Histogram. Meta Length"], ["99MRC"]]],
        [""],
        ["2"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["38"],
        ["ED"],
        [[["15000"], ["WBC Histogram. Binary"], ["99MRC"]]],
        [""],
        [
            [
                [""],
                ["Application"],
                ["Octet-stream"],
                ["Base64"],
                [
                    "AAAAAAAAAAAAAAAAAAAAAAAAANUBCgFAAeAD9QvgD/8P/w//D/8P/w//D/8P/w//D/8NwAjABuAF1QQqAoABqgFAAGoAagCgANUAoABqAGoANQA1AAAAAAA1ADUANQA1AAAAAAA1ADUAAAA1AAAAAAAAAAAAAAAAAAAANQA1ADUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANQA1AAAAAAAAAAAAAAAAAAAANQAAAAAANQA1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
                ],
            ]
        ],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["39"],
        ["NM"],
        [[["15051"], ["RBC Histogram. Left Line"], ["99MRC"]]],
        [""],
        ["29"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["40"],
        ["NM"],
        [[["15052"], ["RBC Histogram. Right Line"], ["99MRC"]]],
        [""],
        ["152"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["41"],
        ["NM"],
        [[["15053"], ["RBC Histogram. Binary Meta Length"], ["99MRC"]]],
        [""],
        ["2"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["42"],
        ["ED"],
        [[["15050"], ["RBC Histogram. Binary"], ["99MRC"]]],
        [""],
        [
            [
                [""],
                ["Application"],
                ["Octet-stream"],
                ["Base64"],
                [
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAAEAAgADAAQABgAIAAwAEAAVABwAJQAwADwASgBbAGsAfgCRAKMAtQDFANYA4wDuAPYA wD/AP0A9wDwAOUA2ADJALkAqwCaAIsAewBsAGAAUgBIAD4ANgAuACcAIQAbABYAEgAOAAsACQAHAAYABQAEAAQAAwADAAIAAgACAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAgABAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAwADAAMAAwADAAMAAwADAAIAAgACAAIAAgACAAEAAQABAAEAAQABAAEAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
                ],
            ]
        ],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["43"],
        ["NM"],
        [[["15111"], ["PLT Histogram. Left Line"], ["99MRC"]]],
        [""],
        ["3"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["44"],
        ["NM"],
        [[["15112"], ["PLT Histogram. Right Line"], ["99MRC"]]],
        [""],
        ["47"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["45"],
        ["NM"],
        [[["15113"], ["PLT Histogram. Binary Meta Length"], ["99MRC"]]],
        [""],
        ["2"],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F\nOBX"],
        ["46"],
        ["ED"],
        [[["15100"], ["PLT Histogram. Binary"], ["99MRC"]]],
        [""],
        [
            [
                [""],
                ["Application"],
                ["Octet-stream"],
                ["Base64"],
                [
                    "AAAAAAAAABcAPABsAKUAywDmAPcA/wD/APsA7QDiANIAwACwAJsAhQBzAGIAUwBHADwAMwAuACoAJQAhACAAHAAaABgAEwARABEAEAAQAA4ADAAMAAwADAAMAAwACgAIAAgABwAIAAgACgAMAAwADAAMAAwADAAQABEAFwAeACU="
                ],
            ]
        ],
        [""],
        [""],
        [""],
        [""],
        [""],
        ["F"],
    ]
]
